## a295
## Carina Rauen Firkowski 
## November 20, 2023
##
## This script updates the resistance raster layers generated by "2-patches-and-
## resistance" with the location of viable culverts and bridges for species.



# Load constants
source("Scripts/0-constants.R")



# Load spatial data ------------------------------------------------------------

# Analysis area
analysisArea <- st_read(dsn = file.path(intermediatesDir),
                        layer = "analysisArea")

# Focal area
focalArea <- st_read(dsn = file.path(intermediatesDir),
                     layer = "focalArea")

# Impact assessment area
impactAreaHW6 <- st_read(dsn = file.path(intermediatesDir),
                         layer = "HW6analysisExtent")

# Culvert and bridges
crossingsRaw <- st_read(dsn = file.path(spatialDataDir, 
                                    "Culverts & Bridges", "Update",
                                    "C2E_EcoCorridors_10242023"),
                        layer = "C2E_EcoCorridors_10242023")

# Template raster
templateRaster <- rast(file.path(outputDir, "Resistance", 
                                 "BLBR_Resistance_AnalysisArea.tif"))

# Crop to analysis area
crossingsAnalysis <- crossingsRaw %>%
  st_transform(crs(analysisArea)) %>%
  st_intersection(analysisArea)



# Parameters -------------------------------------------------------------------

# Buffer culverts by constant (value in meters)
bufferSize <- 30

# Suitable culverts & bridges receive a resistance value of 10
culvertResistancevalue <- 1
bridgeResistancevalue <- 1



# Calculate openness ratio (OR) for culverts -----------------------------------

# Function 
# NOTE: input are in cm and output units are in meters
# Calculation for circular culverts
ORcirc <- function(length, width){ 
  (pi * (0.5 * width/100)^2) / (length/100)
}
# Calculation for box culverts
ORbox <- function(length, width, height){ 
  ((height/100) * (width/100)) / (length/100)
}

# Subset culvert points
culverts <- crossingsAnalysis %>%
  filter(StructureT == "Culvert")
  
# Calculate OR 
culverts$OR <- culverts %>%
  apply(., 1, function(x){
          ifelse(x$StructureS != "Box", 
                 ORcirc(length = x$Barrel_Len, 
                        width = min(x$Diameter_W, x$Diameter_1, na.rm = TRUE)),
                 ORbox(length = x$Barrel_Len, 
                       width = min(x$Diameter_W, x$Diameter_1, na.rm = TRUE), 
                       height = min(x$Height_S1, x$Height_S2, na.Rm = TRUE)))
        })



# Pre-process bridges data -----------------------------------------------------

# Subset bridge points
bridges <- crossingsAnalysis %>%
  filter(StructureT == "Bridge")

# Bridges receive resistance value of 1
bridges <- bridges %>% 
  mutate(Resistance = bridgeResistancevalue)

# Save shapefile
st_write(obj = bridges,
         dsn = file.path(intermediatesDir, "Culverts & Bridges"),
         layer = paste0("bridges"),
         factorsAsCharacter = FALSE,
         overwrite = TRUE,
         append = FALSE,
         driver = "ESRI Shapefile")

# Add buffer
bridgeBuffer <- bridges %>%
  st_buffer(., bufferSize)

# Rasterize
bridgeRaster <- bridgeBuffer %>% 
  rasterize(templateRaster, field = "Resistance")

# Save results
writeRaster(bridgeRaster, 
           file.path(intermediatesDir, "Culverts & Bridges",
                     "bridges_resistance.tif"), 
           overwrite = TRUE) 



# Update resistance per species for current connectivity -----------------------

# Species
speciesList <- c("BLBR", "ODVI", "EMBL")

for(species in speciesList){
  
  # Load resistance
  resistanceRaster <- rast(file.path(outputDir, "Resistance",
                                     paste0(species, 
                                            "_Resistance_AnalysisArea.tif")))
  
  # Set minimum culvert size
  if(species == "BLBR"){
    minCulvertSize <- 0.05   # m
    minHeightWidth <- 30     # cm
    maxLength <- NA          # cm
  }  
  if(species == "EMBL"){
    minCulvertSize <- 0.1
    minHeightWidth <- 50
    maxLength <- 2500
  }  
  if(species == "ODVI"){
    minCulvertSize <- 0.6
    minHeightWidth <- 200
    maxLength <- 9000
  }
  
  
  # Filter culverts ------------------------------
  
  # Keep culverts > minCulvertSize
  culvertsOR <- culverts %>% 
    drop_na(OR) %>%
    #filter(OR > minCulvertSize) %>%
    filter(!is.infinite(OR)) 
  
  # Keep culverts with height and width > minHeightWidth
  # Box culverts
  culvertsBox <- culvertsOR %>%
    filter(StructureS == "Box")
  culvertsBoxHW <- culvertsBox %>%
    filter(Diameter_W >= minHeightWidth) %>%
    filter(Diameter_1 >= minHeightWidth) %>%
    filter(Height_S1 >= minHeightWidth) %>%
    filter(Height_S2 >= minHeightWidth)
  # Circular culverts
  culvertsCir <- culvertsOR %>%
    filter(StructureS != "Box")
  culvertsCirHW <- culvertsCir %>%
    filter(Diameter_W >= minHeightWidth) %>%
    filter(Diameter_1 >= minHeightWidth)

  # Merge box and circular culverts
  culvertsSpp <- rbind(culvertsBoxHW, culvertsCirHW)
  
  # Keep culverts with maximum length < maxLength
  if(!is.na(maxLength)){
    culvertsSpp <- culvertsSpp %>%
      filter(Barrel_Len <= maxLength)
  }
  
  # Add resistance value to filtered culverts
  culvertsSpp <- culvertsSpp %>%
    mutate(Resistance = culvertResistancevalue)
  
  # Keep culverts with light at end
  #culvertsSpp <- culvertsSpp %>%
  #  filter(Light >= "At end")
  
  # For species with suitable culverts
  if(dim(culvertsSpp)[1] != 0){
    
    # Save shapefile
    st_write(obj = culvertsSpp,
             dsn = file.path(intermediatesDir, "Culverts & Bridges"),
             layer = paste0(species, "_culverts_allFilters"),
             factorsAsCharacter = FALSE,
             overwrite = TRUE,
             append = FALSE,
             driver = "ESRI Shapefile") 
    
    # Convert culverts to raster files -------------
    
    # Create a buffer around culvert and bridge points
    culvertBuffer <- culvertsSpp %>%
      st_buffer(., bufferSize)
    
    # Rasterize
    culvertRaster <- culvertBuffer %>% 
      rasterize(templateRaster, field = "Resistance")
    
    # Save results
    writeRaster(culvertRaster, 
               file.path(intermediatesDir, "Culverts & Bridges",
                         paste0(species, "_culvert_resistance.tif")), 
               overwrite = TRUE) 
    
    
    # Combine raster layers ------------------------
    
    resistanceStack <- c(resistanceRaster, culvertRaster, bridgeRaster)
    combinedRaster  <- min(resistanceStack, na.rm = TRUE)
    
    
    # Crop to focal area ---------------------------
    
    combinedMasked <- mask(combinedRaster, focalArea)
    
    
    # Save results ---------------------------------
    
    writeRaster(combinedRaster, 
                file.path(outputDir, "Resistance",
                          paste0(species, "_ResistanceCrossings_AnalysisArea.tif")), 
                overwrite = TRUE)
    writeRaster(combinedMasked, 
                file.path(outputDir, "Resistance",
                          paste0(species, "_ResistanceCrossings_FocalArea.tif")), 
                overwrite = TRUE)
  } 
  if(dim(culvertsSpp)[1] == 0){
    
    # Combine raster layers ------------------------
    
    resistanceStack <- c(resistanceRaster, bridgeRaster)
    combinedRaster  <- min(resistanceStack, na.rm = TRUE)
    
    
    # Crop to focal area ---------------------------
    
    combinedMasked <- mask(combinedRaster, focalArea)
    
    
    # Save results ---------------------------------
    
    writeRaster(combinedRaster, 
                file.path(outputDir, "Resistance",
                          paste0(species, "_ResistanceCrossings_AnalysisArea.tif")), 
                overwrite = TRUE)
    writeRaster(combinedMasked, 
                file.path(outputDir, "Resistance",
                          paste0(species, "_ResistanceCrossings_FocalArea.tif")), 
                overwrite = TRUE)
  }

}


# Update resistance per species for case-study ---------------------------------

# HW6 --------------------------------------------

# Crop culverts and bridges layer to HW6 analysis extent
bridgesHW6 <- bridgeRaster %>%
  mask(impactAreaHW6) %>%
  crop(impactAreaHW6)

# Update resistance
scenarioList <- c("HW6_Baseline", "HW6_Ambitious", "HW6_Intermediate", "HW6_Minimum")

for(species in speciesList){
  for(scenarioName in scenarioList){
  
  # Load resistance
  resistanceRaster <- rast(file.path(intermediatesDir, "Omniscape", 
                                     "Case-studies", "27-Nov-2023",
                                     paste0(species, "_Resistance_", 
                                            scenarioName, ".tif")))
  
  # Crop to analysis extent
  resistanceMask <- resistanceRaster %>%
    mask(impactAreaHW6) %>%
    crop(impactAreaHW6)
  
  # Set minimum culvert size
  if(species == "BLBR")  minCulvertSize <- 0.05
  if(species == "EMBL")  minCulvertSize <- 0.25
  if(species == "ODVI")  minCulvertSize <- 0.6
  
  
  # Filter culverts ------------------------------
  
  # Classify all values > minCulvertSize with resistance = culvertResistancevalue
  culvertsOR <- culverts %>% 
    drop_na(OR) %>%
    filter(OR > minCulvertSize) %>%
    filter(!is.infinite(OR)) %>%
    mutate(Resistance = culvertResistancevalue)
  
  
  # Convert culverts to raster files -------------
  
  # Create a buffer around culvert and bridge points
  culvertBuffer <- culvertsOR %>%
    st_buffer(., bufferSize)
  
  # Rasterize
  culvertRaster <- culvertBuffer %>% 
    rasterize(templateRaster, field = "Resistance")
  
  # Crop and mask
  culvertMask <- culvertRaster %>%
    mask(impactAreaHW6) %>%
    crop(impactAreaHW6)

  
  # Combine raster layers ------------------------
  resistanceStack <- c(resistanceMask, culvertMask, bridgesHW6)
  combinedRaster  <- min(resistanceStack, na.rm = TRUE)
  
  
  # Make sure source and resistance extent are the same 
  sourceRaster <- rast(file.path(
    intermediatesDir, "Omniscape", "Case-studies", "27-Nov-2023",
    paste0(species, "_Source_", scenarioName, ".tif")))
  combinedRasterCopy <- combinedRaster
  finalSource <- setValues(combinedRasterCopy, value=sourceRaster[,])
  
  # Save results ---------------------------------
  
  writeRaster(combinedRaster, 
             file.path(outputDir, "Resistance", "Case-studies",
                       paste0(species, scenarioName, 
                              "_ResistanceCrossings_AnalysisArea.tif")), 
             datatype = "INT2S", NAflag = 9999L, overwrite = TRUE)
  writeRaster(finalSource, 
              file.path(outputDir, "Resistance", "Case-studies",
                        paste0(species, scenarioName, 
                               "_Source_AnalysisArea.tif")), 
              datatype = "INT2S", NAflag = 9999L, overwrite = TRUE)
  
  }
}


